<!DOCTYPE html>
<html lang="uk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Обладнання та дані</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"></head>
<body><main class="app-shell"><header class="app-header"><div><p class="eyebrow">Локальне та AI-розпізнавання</p><h1>Обладнання та дані</h1></div><p class="directory">Папка: <code>{{ $imageDirectory }}</code></p></header>
<nav class="tabs" aria-label="Навігація"><button class="tab-button is-active" type="button" data-tab="recognition">Розпізнавання</button><button class="tab-button" type="button" data-tab="settings">Налаштування AI</button></nav>
<section id="recognition-tab" class="tab-content is-active"><section class="workspace"><aside class="image-panel"><div class="panel-heading"><h2>Зображення</h2><div class="panel-actions"><span>{{ count($images) }}</span><button id="refresh-folder" class="icon-button" type="button" title="Оновити папку зображень" aria-label="Оновити папку зображень"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11a8 8 0 1 0 2.1 5.4M20 4v7h-7"/></svg></button></div></div>
@if ($images === [])<p class="empty-state">У папці немає зображень. Додайте JPG, PNG, WEBP, TIFF або BMP до вказаної папки.</p>
@else @foreach (collect($images)->groupBy('uploaded_on') as $dayImages)<section class="image-day"><div class="image-day-divider"><span>{{ $dayImages->first()['uploaded_label'] }}</span></div><div class="image-grid">@foreach ($dayImages as $image)<article class="image-card" data-image-id="{{ $image['id'] }}" data-image-name="{{ $image['name'] }}"><button class="image-preview" type="button"><img src="{{ url('/images/'.$image['id']) }}" alt="{{ $image['name'] }}" loading="lazy"></button><div class="image-card-footer"><span title="{{ $image['name'] }}">{{ $image['name'] }}</span><button class="image-card-menu" type="button" aria-label="Меню фото">⋮</button></div></article>@endforeach</div></section>@endforeach @endif
</aside><section class="recognition-panel" aria-live="polite"><div class="panel-heading"><h2>Результати</h2><span id="status">Виберіть зображення</span></div><p id="selected-image" class="selected-image">Текст буде розпізнано після натискання на зображення зліва.</p><label class="result-label" for="local-result">Локальний OCR</label><textarea id="local-result" class="result-field" readonly spellcheck="false">Результат з’явиться тут.</textarea><div class="ai-toolbar"><label for="agent-select">AI-агент</label><select id="agent-select" disabled><option value="">Спочатку додайте агента</option></select><button id="recognize-ai" class="primary-button" type="button" disabled>Розпізнати AI</button></div><label class="result-label" for="ai-result">AI-розпізнавання</label><textarea id="ai-result" class="result-field" readonly disabled spellcheck="false">Додайте та виберіть AI-агента у налаштуваннях.</textarea></section></section></section>
<section id="settings-tab" class="tab-content"><section class="settings-panel"><div class="settings-heading"><div><h2>AI-агенти</h2><p>Додавайте скільки завгодно постачальників. API-токен шифрується локально й не показується після збереження.</p></div><button id="add-agent" class="primary-button" type="button">Додати агента</button></div><div id="agent-forms" class="agent-forms"></div></section></section>
<footer class="app-version">by <a id="external-homeandriy" href="https://webbooks.com.ua">homeandriy</a> · v{{ $appVersion }}</footer></main><script>window.initialAiAgents=@json($agents);</script><script src="{{ asset('js/app.js') }}"></script></body></html>
